### ISSUE TITLE
【技术思考第六题】水平垂直居中

### ISSUE THREAD

**Issue by zhouchao941105** [tuia-fed/weekly-question#48]
假设有两个div，父div尺寸为200 * 200，子div尺寸为100 * 100
请写出尽可能多的方法，做到子div在父div中垂直水平居中

**Comment by Nelosen** [comment]
```tsx
//first
.father {
    position: relative;
}
.child {
    position: absolute;;
    top: 50%;
    left: 50%;
    margin-left: -50px;
    margin-top: -50px;
}
//second
.father {
    position: relative;
}
.child {
    position: absolute;;
    top: calc(50% - 50px);
    left: calc(50% - 50px);
}
//third
.father {
    display: flex;
    justify-content: center;
    align-items: center;
}
```

**Comment by nailaowang** [comment]
```jsx
/** 1 flex布局，可不知子元素宽高 **/
.father {
  display: flex;
  justify-content: center;
  align-items: center;
}

/** 2 绝对定位，减去边距，前提是要知道子元素宽高 **/
.father {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  right: 50%;
  margin-left: -50px;
  margin-right: -50px;
}

/** 3 绝对定位 + transform，可不知子元素宽高  **/
.father {
  position: relative;
}
.child {
  position: absolute;
  top: 50%;
  left: 50%;
  transform:  translate(-50%, -50%)
}

/** 4 绝对定位 + margin: auto **/
.father {
  position: relative;
}
.child {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
  margin:  auto;
}

/** 5 绝对定位 + calc **/
.father {
  position: relative;
}
.child {
  position: absolute;
  top: calc(50% - 50px);
  left: calc(50% - 50px);
}

```

**Comment by Joeng3ll** [comment]
```css
// 1、flex
.father {
    display: flex;
    justify-content: center;
    align-items: center;
}

// 2、
.father {
   position: relative;
}

.child {
  position: absoltue;
  top: 50%;
  left: 50%;
  transform:  translate(-50%, -50%);
}

```

**Comment by fly0o0** [comment]
```html
<!DOCTYPE html>
<html>
<head>
  <title>水平垂直居中</title>
  <style type="text/css">
    .outer {
      height: 200px;
      width: 200px;
      background: tomato;
      margin: 10px;
      float: left;
      position: relative;
    }
    .inner {
      height: 100px;
      width: 100px;
      background: black;
    }
    /* 
     * 通过 position 和 margin 居中 
     * 缺点：需要知道 inner 的长宽
     */
    .inner1 {
      position: absolute;
      top: 50%;
      left: 50%;
      margin-top: -50px;
      margin-left: -50px;
    }
    /*
     * 通过 position 和 margin 居中 (2
     */
    .inner2 {
      position: absolute;
      top: 0;
      right: 0;
      bottom: 0;
      left: 0;
      margin: auto;
    }
    /*
     * 通过 flex 进行居中
     */
    .outer3 {
      display: flex;
      justify-content: center;
      align-items: center;
    }
    /**
     * 通过 position 和 transform 居中
     */
    .inner4 {
      top: 50%;
      left: 50%;
      transform: translate(-50%,-50%);
      position: absolute;
    }
  </style>
</head>
<body>
  <div class="outer outer1">
    <div class="inner inner1"></div>
  </div>
  <div class="outer outer2">
    <div class="inner inner2"></div>
  </div>
  <div class="outer outer3">
    <div class="inner inner3"></div>
  </div>
  <div class="outer outer4">
    <div class="inner inner4"></div>
  </div>
</body>
</html>
```

> [demo](https://codepen.io/fly0o0/pen/PoqEgGy)

**Comment by babaloveu** [comment]
```css
1.
.child{
display:inline-block;
text-align:center;
}

2.
.father {
    display: flex;
    justify-content: center;
    align-items: center;
}

3.
.father {
   position: relative;
}

.child {
  position: absoltue;
  top: 50%;
  left: 50%;
  transform:  translate(-50%, -50%);
}
4.
.father{
position:relative
}
.child{
position:absolute;
left:50%;
top:50%;
transform:translate(-50%)
}
```

**Comment by yrZhaoweb** [comment]
```css
.father {
  position： relative
}
.child {
position: absolute;
1.
left: 0;
right: 0;
top: 0;
bottom: 0;
margin: auto;
2. 
left: 50%;
right: 50%;
transform: translate(-50%, -50%);
}
```
