### ISSUE TITLE
【技术思考第七题】CSS权重

### ISSUE THREAD

**Issue by zhouchao941105** [tuia-fed/weekly-question#49]
+ 内联样式
+ 类、伪类选择器
+ id选择器
+ 属性选择器
+ 标签选择器
+ 层级关系选择器

1. 以上这些选择器之间的优先级，从高到低如何排列？
2. 假设下方两条css规则最终都作用于同一个span标签，那么该span的最终宽度是多少？
```css
div#god div.dad span.son {width: 200px;}
div#god span#test {width: 250px;}
```
