### ISSUE TITLE
【技术思考第八题】高清屏下画一条1物理像素的线

### ISSUE THREAD

**Issue by zhouchao941105** [tuia-fed/weekly-question#51]
不同的高清屏，在解析到1px时，实际占用的物理像素，有些是2个物理像素，有些是3个物理像素。在3倍高清下，1px的线就会显的太粗了
Q：在普通屏、2倍高清屏和3倍高清屏下，画出一条长度不限，但高度只有1物理像素的线

**Comment by Nelosen** [comment]
retina屏会以2个（乃至3个）物理像素来显示一个CSS像素（1px），所以在CSS中指定1px的边框实际占据的却是2个以上物理像素
给一个原元素两倍大小的伪元素，指定1px边框，再缩小一半，即可得到0.5px边框。

.retina-border-scale{
            position: relative;
        }
        .retina-border-scale:before{
            content:'';
            border: 1px solid black;
            transform:scale(0.5);
            transform-origin: 0 0;
            width: 200%;height: 200%;
            position: absolute;
            left: 0;
            top: 0;
        }

**Comment by Joeng3ll** [comment]
```css
  .line {
    position: relative;

    &::after {
      display: inline-block;
      content: '';
      position: absolute;
      top: 0;
      bottom: 0;
      left: 0;
      right: 0;
      width: 100%;
      height: 1px;
      transform: scale(1,0.5);
      background: red;
    }
  }
}
```

**Comment by yrZhaoweb** [comment]
```css

.line {	
    background-image: linear-gradient(0deg,black 50%,transparent 50%);	
    background-size: 100% 1px;	
    background-repeat: no-repeat;	
}

```

**Comment by fly0o0** [comment]
transform:scale(0.5) 进行1px的缩放


> [另一种解法来自周成](https://github.com/zhouchengi/postcss-hairlines)

**Comment by babaloveu** [comment]
```css 
.border {
    position: relative;
}

@media screen and (-webkit-min-device-pixel-ratio:2){
.border : before {
      content: '';
      position: absolute;
      top: 0;
      bottom: 0;
      border-top:1px solid #d9d9d9;
      color:#d9d9d9;
      left: 0;
      right: 0;
      width: 100%;
      height: 1px;
      transform: scaleY(0.5);
    }
}
```
