### ISSUE TITLE
【技术思考第九题】css画图形

### ISSUE THREAD

**Issue by zhouchao941105** [tuia-fed/weekly-question#53]
1. 利用css画一个三角形
2. 利用css画一个梯形
3. 六边形呢？

**Comment by yrZhaoweb** [comment]
三角形和梯形都利用超宽的border实现
角度可通过不同方向border宽度任意变换
六边形由两个梯形叠加~
```html
<body>
  <div class="wrap">
    <div class="triangle"></div>
    <div class="trapezoid"></div>
    <div class="hexagon1"></div>
    <div class="hexagon2"></div>
  </div>
</body>
```

```css
.wrap {
  width: 500px;
  height: 100%;
  border: 1px solid black;
}
.triangle {
  width: 0px;
  height: 0px;
  border-top: 0px solid transparent;
  border-left: 200px solid transparent;
  border-right: 200px solid transparent;
  border-bottom: 300px solid blue;
}
.trapezoid {
  height: 50px;
  border-top: 150px solid transparent;
  border-left: 150px solid transparent;
  border-right: 150px solid transparent;
  border-bottom: 150px solid blue;
}
.hexagon1 {
  height: 50px;
  border-top: 150px solid transparent;
  border-left: 150px solid transparent;
  border-right: 150px solid transparent;
  border-bottom: 150px solid blue;
}
.hexagon2 {
  height: 50px;
  border-top: 150px solid blue;
  border-left: 150px solid transparent;
  border-right: 150px solid transparent;
  border-bottom: 150px solid transparent;
}
```

效果图
![image](https://user-images.githubusercontent.com/38726783/98618016-3be77800-233b-11eb-916e-75adabcc764f.png)

**Comment by nailaowang** [comment]
```jsx
<div className="triangle"></div>
<div className="trapezoid"></div>
     
<div className="sixangle">
    <div className="triangle_top"></div>
    <div className="triangle_bottom"></div>
</div>
```
```css
.triangle {
  width: 0px;
  height: 0px;
  border-bottom: 100px solid #ccc;
  border-top: 100px solid transparent;
  border-left: 100px solid transparent;
  border-right: 100px solid transparent;
}

.trapezoid{
  width: 100px;
  height: 0px;
  border-bottom: 70px solid #ccc;
  border-top: 70px solid transparent;
  border-left: 70px solid transparent;
  border-right: 70px solid transparent;
}

.triangle_top {
  width: 100px;
  height: 0px;
  border-bottom: 70px solid #ccc;
  border-top: 70px solid transparent;
  border-left: 70px solid transparent;
  border-right: 70px solid transparent;
}
.triangle_bottom{
  width: 100px;
  height: 0px;
  border-top: 70px solid #ccc;
  border-bottom: 70px solid transparent;
  border-left: 70px solid transparent;
  border-right: 70px solid transparent;
}
```

**Comment by Nelosen** [comment]
```jsx
//三角形
    <div class="triangle"></div>
        .triangle{
            width: 0px;                          
            height: 0px;
            border-bottom: 200px solid #00a3af;
            border-left: 200px solid transparent;   
            border-right: 200px solid transparent;
        }
//梯形
<div class="mask"></div>
.mask{
      width:400px;
      height:0;
      border-top:100px solid;
      border-left:100px solid transprant;
      border-right:100px solid transprant;
}
```

**Comment by babaloveu** [comment]
```
.triangle{
    width: 0;
    height: 0;
    border-left: 50px solid transparent;
    border-right: 50px solid transparent;
    border-top: 100px solid red;
}
.tx{
    height: 0;
    width: 100px;
    border-top: 100px solid red;
    border-right: 37px solid transparent;
}
.lbx{
    width: 100%;
    height: 100%;
    overflow: hidden;
    transform: rotate(-60deg);
    background-color: red;
　}

```

**Comment by Joeng3ll** [comment]
```css
.box {
    /* 内部大小 */
    width: 0px;
    height: 0px;
    /* 边框大小 只设置三条边*/
    border-top: #4285f4 solid;
    border-right: transparent solid;
    border-left: transparent solid;
    border-width: 85px; 
    /* 其他设置 可有可无*/
    margin: 50px;
}

```
