### ISSUE TITLE
【技术思考第十题】line-height、font-size与行距的关系

### ISSUE THREAD

**Issue by zhouchao941105** [tuia-fed/weekly-question#55]
1. line-height有哪些值可以填，当其为相对值时，是相对于什么值来计算最终值的？
2. 设置了height:60px;line-height:60px;后，里面的字体就居中了，原因是什么？ [demo](https://codesandbox.io/s/keen-wildflower-lzsf8?file=/index.html)

**Comment by nailaowang** [comment]
```jsx
  line-height: normal;  // 默认,取决于用户端；
  line-height: 1.5;  // 行高 = 1.5 * 字体大小
  line-height: 10px;  // 行高固定
  line-height: 10%;  // 基于当前字体尺寸的百分比行
  line-height: inherit;  // 继承于父元素
```
2. 文本行高等于容器高度，文本在文本行高中是居中的，所以文本在容器中看起来也是垂直居中的
    http://www.imooc.com/article/7767

**Comment by Nelosen** [comment]
```jsx
line-height:normal；//默认
line-height: 1 //设置数字，此数字会与当前的字体尺寸相乘来设置行间距
line-height: 10px //固定行间距
line-height: 10% //基于当前字体尺寸的百分比行间距
line-height: inherit;  // 规定应该从父元素继承 line-height 属性的值。
```

**Comment by yrZhaoweb** [comment]
```css
.text {
  line-height: normal; // 默认属性 取决于客户端，如 font-famliy
  line-height: 1; //取数字 = = >  行高 = 数字 * 字体大小
  line-height: 10px;  // 固定行高为多少PX，一般用行高 = 元素高来垂直居中
  line-height: 10%;  // 基于字体大小
  line-height: inherit; // 继承父元素
}
```
