### ISSUE TITLE
【技术思考第十一题】多行文本的垂直居中

### ISSUE THREAD

**Issue by zhouchao941105** [tuia-fed/weekly-question#56]
[demo](https://codesandbox.io/s/new-hill-j55q1?file=/index.html)
增加css属性，使得这段文本在父级盒子中垂直居中

**Comment by Joeng3ll** [comment]
```css
      .container {
        height: 180px;
++      line-height: 180px;
        background: pink;
++      text-align: center;
      }
      .box {
        display: inline-block;
        background: yellow;
        line-height: 20px;
        vertical-align: middle;
      }
```

**Comment by nailaowang** [comment]
```jsx
// 父元素height,line-height相同
      .container {
        height: 180px;
        line-height: 180px;
        background: pink;
      }
      .box {
        display: inline-block;
        background: yellow;
        line-height: 20px;
        vertical-align: middle;
      }
// 利用display:table 布局
.container {
    height: 180px;
    background: pink;
    display: table;
}
.box {
    display: table-cell;
    background: yellow;
    line-height: 20px;
    vertical-align: middle;
}
```

**Comment by Nelosen** [comment]
```less
.container {
        height: 180px;
        line-height: 180px;
        text-align: center;
        background: pink;
      }
```

**Comment by yrZhaoweb** [comment]
```css
 .container {
   height: 180px;
   background: pink;
   /* changes */
   line-height: 180px;
}
```

**Comment by fly0o0** [comment]
[demo](https://codepen.io/fly0o0/pen/gOMVLqa)

**Comment by babaloveu** [comment]
```css
 .container {
        height: 180px;
        background: pink;
        display: table;
      }
      .box {
        background: yellow;
        line-height: 20px;
        display: table-cell;
        vertical-align: middle;
        text-align: center;
      }
```
